/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVideoRouteImport } from './routes/api/video'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAdminRouteImport } from './routes/api/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/data': typeof ApiDataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/video': typeof ApiVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/data': typeof ApiDataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/video': typeof ApiVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/data': typeof ApiDataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/video': typeof ApiVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/api/auth'
    | '/api/data'
    | '/api/media'
    | '/api/payments'
    | '/api/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/api/auth'
    | '/api/data'
    | '/api/media'
    | '/api/payments'
    | '/api/video'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/api/auth'
    | '/api/data'
    | '/api/media'
    | '/api/payments'
    | '/api/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiVideoRoute: typeof ApiVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiDataRoute: ApiDataRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiVideoRoute: ApiVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
